spring:
  application:
    name: ${MESH_SVC_NAME:nacos-dubbo-demo-provider}
demo:
  service:
    version: 1.0.0
    group: nacos-dubbo

dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
    parameters:
      namespace: ${NACOS_NAMESPACE}
      group: ${NACOS_GROUP}
      ignoreCheckKeys: username,password
  provider:
    parameters:
      isjoin: ${MESH_SWITCHER_MESH}
      deploy: ${DEPLOY_TYPE}
      svcname: ${K8S_NAMESPACE}:${MESH_SVC_NAME}
      paas-name: ${MESH_SVC_NAME:nacos-dubbo-demo-provider}
      paas-ns: ${K8S_NAMESPACE:apm}
      service-type: Dubbo
