spring:
  application:
    name: multi-protocol-demo-provider
demo:
  service:
    version: 1.0.0
    group: nacos-dubbo

dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://192.168.0.201:32558?username=nacos&password=nacos
    parameters:
      namespace: public
      ignoreCheckKeys: username,password
  provider:
    parameters:
      isjoin: true
      deploy: container
      svcname: default:multi-protocol-demo-provider